const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const pageSource = fs.readFileSync(path.join(__dirname, "..", "app", "page.tsx"), "utf8");

assert.match(pageSource, /步骤 1：上传论文/);
assert.match(pageSource, /步骤 2：粘贴格式要求/);
assert.match(pageSource, /先帮你读懂老师要求，再按确认后的规则修改 Word/);
assert.match(pageSource, /当前排版方案：/);
assert.match(pageSource, /老师没单独说明的地方，会按这个方案的默认规则处理/);
assert.match(pageSource, /正文、标题、摘要关键词、图题表题、参考文献和页边距/);
assert.match(pageSource, /高级设置（一般无需修改）/);
assert.match(pageSource, /查看默认会处理哪些内容/);
assert.match(pageSource, /这里只列出老师明确提到的格式/);
assert.match(pageSource, /我已确认以上识别出的格式规则/);
assert.match(pageSource, /请先确认识别出的格式规则/);
assert.match(pageSource, /重新识别/);
assert.match(pageSource, /改用快速识别/);
assert.match(pageSource, /返回修改要求/);
assert.match(pageSource, /正在理解格式要求，复杂内容可能需要 20-60 秒/);
assert.match(pageSource, /还在理解复杂要求，可以继续等待，也可以改用快速识别/);
assert.match(pageSource, /解析成功并确认规则前不会修改 Word/);
assert.match(pageSource, /notice-block/);
assert.match(pageSource, /raw_ai_rules/);
assert.match(pageSource, /normalized_ai_rules/);
assert.match(pageSource, /整理后的老师要求/);
assert.match(pageSource, /canonicalRequirementsText/);
assert.match(pageSource, /parsedRules/);
assert.match(pageSource, /validatedRules/);
assert.match(pageSource, /requirementsText\.trim\(\) && !parsedOverride/);
assert.match(pageSource, /通用论文方案/);
assert.match(pageSource, /课程论文方案/);
assert.match(pageSource, /templateName \|\| "default"/);
assert.match(pageSource, /显示\/隐藏编辑标记/);
assert.match(pageSource, /不属于正文内容/);
assert.match(pageSource, /不影响打印和提交/);
assert.match(pageSource, /发现几处要求前后不太一致/);
assert.match(pageSource, /建议你看一眼/);
assert.match(pageSource, /有些格式要求前后不太一致/);
assert.match(pageSource, /这次识别到的论文内容/);
assert.match(pageSource, /系统只会修改比较确定的部分/);
assert.match(pageSource, /不会强行改/);
assert.match(pageSource, /需要注意的地方/);
assert.match(pageSource, /这段标题的样式和编号不一致/);
assert.match(pageSource, /系统已经按编号处理/);

console.log("ui copy tests passed");
